create table map_file ( id TEXT NOT NULL, filename TEXT NOT NULL, name TEXT NOT NULL, unit_x TEXT NOT NULL, unit_y TEXT NOT NULL, center_x TEXT NOT NULL, center_y TEXT NOT NULL, cache_name TEXT NOT NULL, primary key (id));
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (1, 'am.png', 'Ankh-Morpork', 14, 14, 718, 802, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (2,  'am_assassins.png', 'AM Assassins', 28, 28, 457, 61, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (3, 'am_buildings.png', 'AM Buildings', 25, 25, 208, 76, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (4, 'am_cruets.png', 'AM Cruets', 24, 24, 300, 69, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (5, 'am_docks.png', 'AM Docks', 14, 14, 174, 216, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (6, 'am_guilds.png', 'AM Guilds', 28, 28, 487, 245, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (7, 'am_isle_gods.png', 'AM Isle of Gods', 24, 24, 342, 587, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (8, 'am_shades.png', 'Shades Maze', 80, 80, 46, 179, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (9, 'am_smallgods.png', 'Temple of Small Gods', 24, 24, 221, 224, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (10, 'am_temples.png', 'AM Temples', 24, 24, 575, 419, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (11, 'am_thieves.png', 'AM Thieves', 28, 28, 431, 300, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (12, 'am_uu.png', 'Unseen University', 28, 28, 166, 393, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (13, 'am_warriors.png', 'AM Warriors', 32, 25, 135, 104, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (14, 'am_watch_house.png', 'Pseudopolis Watch House', 24, 24, 88, 104, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (15, 'magpyr.png', $$Magpyr's Castle$$, 20, 20, 141, 440, 'Magpyr');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (16, 'bois.png', 'Bois', 14, 14, 239, 169, 'Bois');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (17, 'bp.png', 'Bes Pelargic', 14, 14, 1070, 748, 'BP');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (18, 'bp_buildings.png', 'BP Buildings', 24, 24, 428, 177, 'BP');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (19, 'bp_estates.png', 'BP Estates', 14, 14, 540, 506, 'BP');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (20, 'bp_wizards.png', 'BP Wizards', 20, 20, 101, 517, 'BP');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (21, 'brown_islands.png', 'Brown Islands', 28, 28, 105, 101, 'Brown');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (22, 'deaths_domain.png', $$Death's Domain$$, 28, 28, 98, 86, 'Death');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (23, 'djb.png', 'Djelibeybi', 14, 14, 438, 369, 'DJB');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (24, 'djb_wizards.png', 'IIL - DJB Wizards', 28, 28, 210, 210, 'DJB');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (25, 'ephebe.png', 'Ephebe', 14, 14, 407, 349, 'Ephebe');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (26, 'ephebe_under.png', 'Ephebe Underdocks', 14, 14, 247, 285, 'Ephebe');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (27, 'genua.png', 'Genua', 14, 14, 470, 242, 'Genua');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (28, 'genua_sewers.png', 'Genua Sewers', 21, 21, 405, 312, 'Genua');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (29, 'grflx.png', 'GRFLX Caves', 20, 20, 303, 222, 'GRFLX');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (30, 'hashishim_caves.png', 'Hashishim Caves', 28, 28, 258, 133, 'Klatch');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (31, 'klatch.png', 'Klatch Region', 14, 14, 724, 515, 'Klatch');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (32, 'lancre_castle.png', 'Lancre Region', 14, 14, 285, 33, 'Ramtops');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (33, 'mano_rossa.png', 'Mano Rossa', 28, 28, 298, 202, 'Genua');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (34, 'monks_cool.png', 'Monks of Cool', 14, 14, 113, 170, 'Ramtops');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (35, 'netherworld.png', 'Netherworld', 14, 14, 42, 75, 'Nether');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (37, 'pumpkin_town.png', 'Pumpkin Town', 48, 48, 375, 194, 'Pumpkin');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (38, 'ramtops.png', 'Ramtops Regions', 14, 14, 827, 223, 'Ramtops');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (39, 'sl.png', 'Sto-Lat', 14, 14, 367, 222, 'Sto-Lat');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (40, 'sl_aoa.png', 'Academy of Artificers', 25, 25, 47, 87, 'Sto-Lat');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (41, 'sl_cabbages.png', 'Cabbage Warehouse', 28, 28, 60, 92, 'Sto-Lat');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (42, 'sl_library.png', 'AoA Library', 57, 57, 220, 411, 'Sto-Lat');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (43, 'sl_sewers.png', 'Sto-Lat Sewers', 14, 14, 162, 204, 'Sto-Lat');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (44, 'sprite_caves.png', 'Sprite Caves', 14, 14, 113, 182, 'Sprites');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (45, 'sto_plains.png', 'Sto Plains Region', 14, 14, 752, 390, 'Sto-Plains');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (46, 'uberwald.png', 'Uberwald Region', 14, 14, 673, 643, 'Uber');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (47, 'uu_library_full.png', 'UU Library', 30, 30, 165, 4810, 'UU');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (48, 'farmsteads.png', 'Klatchian Farmsteads', 28, 28, 445, 171, 'Klatch');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (49, 'ctf_arena.png', 'CTF Arena', 48, 48, 307, 283, 'CTF');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (50, 'pk_arena.png', 'PK Arena', 30, 30, 155, 331, 'PK');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (51, 'am_postoffice.png', 'AM Post Office', 28, 28, 156, 69, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (52, 'bp_ninjas.png', 'Ninja Guild', 28, 28, 109, 56, 'BP');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (53, 'tshop.png', 'The Travelling Shop', 28, 28, 355, 315, 'T-Shop');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (54, 'slippery_hollow.png', 'Slippery Hollow', 14, 14, 215, 123, 'S-Hollow');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (55, 'creel_guild.png', 'House of Magic - Creel', 28, 28, 38, 86, 'Ramtops');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (56, 'quow_specials.png', 'Special Areas', 28, 28, 288, 28, 'Misc');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (57, 'skund_wolftrails.png', 'Skund Wolf Trail', 12, 12, 41, 587, 'Skund');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (58, 'medina.png', 'Medina', 38, 38, 131, 126, 'BP');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (59, 'copperhead.png', 'Copperhead', 12, 12, 55, 47, 'Copper');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (60, 'ephebe_citadel.png', 'The Citadel', 11, 11, 37, 74, 'Ephebe');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (61, 'am_fools.png', $$AM Fools' Guild$$, 28, 28, 135, 101, 'AM');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (62, 'thursday.png', $$Thursday's Island$$, 28, 28, 112, 65, 'Thursday');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (63, 'unsinkable.png', 'SS Unsinkable', 28, 28, 143, 124, 'Unsinkable');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (64, 'passages.png', 'Passage Rooms', 28, 28, 68, 28, 'Passages');
insert into map_file (id, filename, name, unit_x, unit_y, center_x, center_y, cache_name) values (99, 'discwhole.png', 'Whole Disc', 1, 1, 1175, 3726, 'Terrains');